var foods = [
  {
    id: 1,
    title: 'Healthy Meal Plan',
    sub_title: 'How we dream about our future',
    type: 'lunch',
    details: 'Food Description is here.',
    price: 23.99,
    img: 'lunch1.png',
  },
  {
    id: 2,
    title: 'Fried Chicken Bento',
    sub_title: 'How we dream about our future',
    type: 'lunch',
    details: 'Food Description is here.',
    price: 9.99,
    img: 'lunch2.png',
  },
  {
    id: 3,
    title: 'Tarragon-Rubbed-Salmon',
    sub_title: 'How we dream about our future',
    type: 'lunch',
    details: 'Food Description is here.',
    price: 6.99,
    img: 'lunch3.png',
  },
  {
    id: 4,
    title: 'Indian Lunch',
    sub_title: 'How we dream about our future',
    type: 'lunch',
    details: 'Food Description is here.',
    price: 8.99,
    img: 'lunch4.png',
  },
  {
    id: 5,
    title: 'Beef Steak',
    sub_title: 'How we dream about our future',
    type: 'lunch',
    details: 'Food Description is here.',
    price: 15.99,
    img: 'lunch5.png',
  },
  {
    id: 6,
    title: 'Honey-Soy-Glazed Salmon with Poppers',
    sub_title: 'How we dream about our future',
    type: 'lunch',
    details: 'Food Description is here.',
    price: 7.99,
    img: 'lunch6.png',
  },
  {
    id: 7,
    title: 'Bagel and cream cheese',
    sub_title: 'How we dream about our future',
    type: 'breakfast',
    details: 'Food Description is here.',
    price: 6.99,
    img: 'breakfast1.png',
  },
  {
    id: 8,
    title: 'Breakfast sandwich',
    sub_title: 'How we dream about our future',
    type: 'breakfast',
    details: 'Food Description is here.',
    price: 9.99,
    img: 'breakfast2.png',
  },
  {
    id: 9,
    title: 'Baked Chiken',
    sub_title: 'How we dream about our future',
    type: 'breakfast',
    details: 'Food Description is here.',
    price: 10.99,
    img: 'breakfast3.png',
  },
  {
    id: 10,
    title: 'Eggs Benedict',
    sub_title: 'How we dream about our future',
    type: 'breakfast',
    details: 'Food Description is here.',
    price: 8.99,
    img: 'breakfast4.png',
  },
  {
    id: 11,
    title: 'Tast Croissarit Fried egg',
    sub_title: 'How we dream about our future',
    type: 'breakfast',
    details: 'Food Description is here.',
    price: 19.99,
    img: 'breakfast5.png',
  },
  {
    id: 12,
    title: 'Full Breakfast Fried Egg Toast Brunch',
    sub_title: 'How we dream about our future',
    type: 'breakfast',
    details: 'Food Description is here.',
    price: 3.99,
    img: 'breakfast6.png',
  },
  {
    id: 13,
    title: 'Salmon with Grapefruit and Lentil Salad',
    sub_title: 'How we dream about our future',
    type: 'dinner',
    details: 'Food Description is here.',
    price: 9.99,
    img: 'dinner1.png',
  },
  {
    id: 14,
    title: 'Lemony Salmon Piecata',
    sub_title: 'How we dream about our future',
    type: 'dinner',
    details: 'Food Description is here.',
    price: 10.99,
    img: 'dinner2.png',
  },
  {
    id: 15,
    title: 'Pork tenderloin with Quinea Pilaf',
    sub_title: 'How we dream about our future',
    type: 'dinner',
    details: 'Food Description is here.',
    price: 12.99,
    img: 'dinner3.png',
  },
  {
    id: 16,
    title: 'French fries with cheese',
    sub_title: 'How we dream about our future',
    type: 'dinner',
    details: 'Food Description is here.',
    price: 8.99,
    img: 'dinner4.png',
  },
  {
    id: 17,
    title: 'Garlic Butter Baked Salmon',
    sub_title: 'How we dream about our future',
    type: 'dinner',
    details: 'Food Description is here.',
    price: 6.99,
    img: 'dinner5.png',
  },
  {
    id: 18,
    title: 'Baked Chiken',
    sub_title: 'How we dream about our future',
    type: 'dinner',
    details: 'Food Description is here.',
    price: 9.99,
    img: 'dinner6.png',
  },
];

export default foods;
